# Generated by Django 4.1 on 2023-10-23 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='answer_image_url',
        ),
        migrations.RemoveField(
            model_name='card',
            name='question_image_url',
        ),
    ]
