# Generated by Django 4.1 on 2023-08-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_card_deck_alter_card_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
