# Generated by Django 4.1 on 2023-08-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_card_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
    ]
