# Generated by Django 4.1 on 2023-08-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_deck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
